import re
import time
from src.agents.tools import TOOL_SPECS, DISPATCH, call_tool, get_region_info, assess_region, list_exposed_assets, get_model_metrics
from src.agents.llm import has_llm, client, SYSTEM_PROMPT
from src.config import LLM_MODEL

MAX_TOOL_CALLS = 8

PLACES = {
    "hitoyoshi": (32.795, 130.755), "city center": (32.795, 130.755), "downtown": (32.795, 130.755),
    "upstream": (32.77, 130.70), "kuma upper": (32.77, 130.70),
    "downstream": (32.83, 130.80), "kuma lower": (32.83, 130.80),
}

def parse_query(q: str) -> dict:
    ql = q.lower()
    m = re.search(r"(-?\d{1,2}\.\d+)\s*[,/]\s*(-?\d{2,3}\.\d+)", q)
    if m:
        lat, lon = float(m.group(1)), float(m.group(2))
    else:
        lat, lon = None, None
        for name, (la, lo) in PLACES.items():
            if name in ql:
                lat, lon = la, lo
                break
        if lat is None:
            lat, lon = PLACES["city center"]
    r = re.search(r"(\d+(?:\.\d+)?)\s*km", ql)
    radius = float(r.group(1)) if r else 2.0
    return {"lat": lat, "lon": lon, "radius_km": radius}

def deterministic_report(query: str) -> dict:
    log = []
    region = call_tool("get_region_info", {}, log)
    parsed = parse_query(query)
    risk = call_tool("assess_region", {"lat": parsed["lat"], "lon": parsed["lon"]}, log)
    assets = call_tool("list_exposed_assets", {"lat": parsed["lat"], "lon": parsed["lon"], "radius_km": parsed["radius_km"]}, log)
    metrics = call_tool("get_model_metrics", {}, log)

    band = "HIGH" if risk["risk_score"] >= 0.5 else ("MODERATE" if risk["risk_score"] >= 0.2 else "LOW")
    top_assets = assets["assets"][:5]
    lines = [
        f"# Flood Risk Assessment — {region['name']}", "",
        f"**Query:** {query}", "",
        "## Summary",
        f"Estimated flood-susceptibility risk at ({parsed['lat']:.3f}, {parsed['lon']:.3f}) is **{band}** "
        f"(model score {risk['risk_score']:.2f}). {assets['n_assets']} client assets fall within {parsed['radius_km']} km, "
        f"with a combined exposure of ¥{assets['total_value_jpy']:,}.", "",
        "## Risk Assessment",
        f"- Nearest evaluated grid cell: {risk['nearest_grid_cell']}",
        f"- Elevation: {risk['drivers']['elev_m']:.1f} m, height above nearest drainage: {risk['drivers']['hand_m']:.1f} m",
        f"- Distance to Kuma River: {risk['drivers']['river_dist_m']:.0f} m",
        f"- Rainfall during event window: {risk['drivers']['rain_flood_mm']:.0f} mm (anomaly vs baseline: +{risk['drivers']['rain_anomaly_mm']:.0f} mm)",
        "", "## Exposed Assets (top 5 by risk)",
    ]
    if top_assets:
        for a in top_assets:
            lines.append(f"- {a['asset_id']} ({a['building_type']}, ¥{a['value_jpy']:,}) — {a['dist_km']} km away, risk {a['risk_score']}")
    else:
        lines.append("- No client assets registered within the search radius.")
    lines += [
        "", "## Confidence & Limitations",
        f"- Model: {metrics['selected_model']}, cross-validated F1={metrics['cv_metrics'][metrics['selected_model']]['f1']:.2f}, "
        f"ROC-AUC={metrics['cv_metrics'][metrics['selected_model']]['roc_auc']}.",
        f"- {metrics['caveat']}",
        "- Generated by the deterministic fallback narrator (no LLM API key configured); numbers are identical to the LLM path, only phrasing differs.",
        "", "## Recommended Actions",
        "- Field-verify highest-risk assets before acting on this PoC output.",
        "- Prioritize inspection of exposed low-elevation/near-river assets flagged above.",
    ]
    return {"report_markdown": "\n".join(lines), "tool_log": log, "mode": "deterministic_fallback"}

def llm_report(query: str) -> dict:
    log = []
    c = client()
    messages = [{"role": "user", "content": query}]
    for _ in range(MAX_TOOL_CALLS):
        resp = c.messages.create(model=LLM_MODEL, max_tokens=1500, system=SYSTEM_PROMPT, tools=TOOL_SPECS, messages=messages)
        messages.append({"role": "assistant", "content": resp.content})
        if resp.stop_reason != "tool_use":
            text = "".join(b.text for b in resp.content if b.type == "text")
            return {"report_markdown": text, "tool_log": log, "mode": "llm_agent"}
        tool_results = []
        for block in resp.content:
            if block.type != "tool_use":
                continue
            if block.name not in DISPATCH:
                out = {"error": "tool not permitted"}
            else:
                out = call_tool(block.name, block.input, log)
            tool_results.append({"type": "tool_result", "tool_use_id": block.id, "content": str(out)})
        messages.append({"role": "user", "content": tool_results})
    return {"report_markdown": "agent exceeded tool-call budget without finishing.", "tool_log": log, "mode": "llm_agent_truncated"}

def run_agent(query: str) -> dict:
    t0 = time.time()
    result = llm_report(query) if has_llm() else deterministic_report(query)
    result["latency_ms"] = round((time.time() - t0) * 1000, 1)
    result["query"] = query
    return result
